// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TheBallCoreABS.TheBallCore
{
    using System;
    using System.IO;
    using System.Xml;
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Linq;
    using System.Xml.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class KnockoutDustHtmlViewGenerator_v1_0 : KnockoutDustHtmlViewGenerator_v1_0Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            this.Write("\r\n");
            
            #line 18 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
   
	// Set abstraction specific type and single file specific extension
	//TransformGenerator< ClassModelAbstractionType >(GenerateRoot, ".designer.cs");	
	GenerateRoot();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 23 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
 
	public Tuple<string, string>[] GetGeneratorContent(params string[] xmlFileNames)
	{
		List<Tuple<string, string>> result = new List<Tuple<string, string>>();
		foreach(string xmlFileName in xmlFileNames)
		{
			TheBallCoreAbstractionType abs = LoadXml<TheBallCoreAbstractionType>(xmlFileName);
			CurrentAbstraction = abs;
			if(abs.InstanceOfTheBall.DigitalInterface == null || abs.InstanceOfTheBall.DigitalInterface.InterfaceViews == null)
				continue;
			InstanceOfTheBallType instance = abs.InstanceOfTheBall;
			CurrInstance = instance;
			foreach(var interfaceObject in abs.InstanceOfTheBall.DigitalInterface.InterfaceModel)
            {
				CurrObject = interfaceObject;
				this.GenerationEnvironment.Clear();
				string content = TransformText();
				string outputFileName = CurrInstance.semanticDomainName + "." + CurrObject.name + ".admgen.ts";
				//string outputFile = Path.GetFileNameWithoutExtension(xmlFileName) + ".admgen.ts";
				result.Add(Tuple.Create(outputFileName, content));
            }
		}
		return result.ToArray();
	}
	
	void SetCurrentAbstraction(object abs)
	{
		CurrentAbstraction = ( TheBallCoreAbstractionType ) abs;
	}
	
	TheBallCoreAbstractionType CurrentAbstraction;
	InterfaceObjectType CurrObject;
	InstanceOfTheBallType CurrInstance;
	
	void GenerateRoot()
	{
		if(CurrObject == null)
			return;
		GenerateInterfaceObject(CurrObject);
	}

	string GetTSDataType(InterfaceItemTypeLogicalDataType logicalDataType)
    {
		switch (logicalDataType)
		{
			case InterfaceItemTypeLogicalDataType.Text_Long:
			case InterfaceItemTypeLogicalDataType.Text_Short:
				return "string";
			case InterfaceItemTypeLogicalDataType.Time_Date:
			case InterfaceItemTypeLogicalDataType.Time_Time:
			case InterfaceItemTypeLogicalDataType.Time_DateTime:
				return "Date";
			case InterfaceItemTypeLogicalDataType.Number:
				return "number";
			default:
				throw new NotSupportedException("Logical data type not supported: " + logicalDataType);
		}
    }

	InterfaceObjectType GetInterfaceObjectByName(string interfaceObjectName)
    {
		var result = CurrInstance.DigitalInterface.InterfaceModel.FirstOrDefault(candidate => candidate.name == interfaceObjectName);
		if(result == null)
			throw new ArgumentException("Interface object not found with name: " + interfaceObjectName);
		return result;
    }

	void GenerateInterfaceObject(InterfaceObjectType iObj)
    {
		string objectName = iObj.name;


        
        #line default
        #line hidden
        
        #line 94 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write("class ");

        
        #line default
        #line hidden
        
        #line 95 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(objectName));

        
        #line default
        #line hidden
        
        #line 95 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write(" {\r\n");

        
        #line default
        #line hidden
        
        #line 96 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
 GenerateInterfaceItems(iObj.InterfaceItems); 
        
        #line default
        #line hidden
        
        #line 96 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write("}\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 99 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"

    }

	void GenerateInterfaceItems(object[] interfaceItems)
    {
		foreach (var item in interfaceItems)
		{
			string itemName;
			string dataType;
			InterfaceItemType iItem = item as InterfaceItemType;
			ObjectInstanceType oItem = item as ObjectInstanceType;
			dynamic dynItem = item;
			string collectionPostFix = dynItem.isCollection ? "[]" : "";
			if(iItem != null) {
				dataType = GetTSDataType(iItem.logicalDataType);
				itemName = iItem.name;
            } else if(oItem != null) {
				dataType = oItem.interfaceObjectName;
				itemName = oItem.name;
            } else
				throw new NotSupportedException("InterfaceItem type not supported: " + item.GetType().Name);



        
        #line default
        #line hidden
        
        #line 122 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write("\t");

        
        #line default
        #line hidden
        
        #line 123 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(itemName));

        
        #line default
        #line hidden
        
        #line 123 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write(": ");

        
        #line default
        #line hidden
        
        #line 123 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataType));

        
        #line default
        #line hidden
        
        #line 123 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(collectionPostFix));

        
        #line default
        #line hidden
        
        #line 123 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 124 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\KnockoutDustHtmlViewGenerator_v1_0.tt"

		}
    }

	

        
        #line default
        #line hidden
        
        #line 2 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
 
	enum AbstractionShareLevel
	{
		Local,
		Shared,
		Modular,
	}
	
	bool IsLocal
	{
		get {
			return ShareLevel == AbstractionOptions.GeneralTypeShareLevel.Local;
		}
	}
	
	AbstractionOptions.AbstractionOptionsType CurrentOptions;
	AbstractionOptions.GeneralTypeShareLevel ShareLevel {
		get {
			return CurrentOptions.General.shareLevel;
		}
	}
	
	void TransformGenerator<AbstractionType>(Action rootLevelGenerator, string sharedSingleFileExtension)
	{
		// Abstraction(s) that are supposed to be shared must be shared by default.
		// This is simply because any change to "shared" makes it modified compared to the shared version.
		// Thus making abstraction "local" allows also making the changes that make it behave like "local".
		// To make the abstraction "local" make following changes:
		// 1. Modify the output - directive right on top of the file (2nd line) from "?" to ".designer.cs"
		// 2. Set the AbstractionShareLevel below to Shared 
		// 3. After the changes, the abstraction starts to generate its output right below the template:
		// - Change the .cs file properties so that it doesn't compile in the abstraction-project
		// - Link the output .cs file to appropriate projects (to replace the links from AbstractionContent/Out directory)
		// 4. If necessary, copy over and alter the include-files specified for common includes
		
		// ShareLevel = AbstractionShareLevel.Shared;
		
		string templateDirectoryPath = Path.GetDirectoryName(Host.TemplateFile);
		DirectoryInfo dirInfo = new DirectoryInfo(templateDirectoryPath);
		dirInfo = dirInfo.Parent;
		string optionsFile = Path.Combine(dirInfo.FullName, "Options.xml");
		CurrentOptions = LoadXml<AbstractionOptions.AbstractionOptionsType>(optionsFile);

		if(ShareLevel != AbstractionOptions.GeneralTypeShareLevel.Modular)
		{
			string directoryName = GetContentDirectoryFromTemplateFullPath(Host.TemplateFile, IsLocal == false);
			string[] xmlFileNames = Directory.GetFiles(directoryName, "*.xml");
			
			foreach(string xmlFileName in xmlFileNames)
			{
				AbstractionType current = LoadXml<AbstractionType>(xmlFileName);
				SetCurrentAbstraction(current);
				rootLevelGenerator();
			}
		} 
		else
		{
			rootLevelGenerator();
		}
		
		if(ShareLevel == AbstractionOptions.GeneralTypeShareLevel.Shared)
		{
			WriteContentToSingleOutput(Host.TemplateFile, sharedSingleFileExtension);
		}
	}
	
	
	string GetContentDirectoryFromTemplateFullPath(string templateFullPath, bool isShared)
	{
		string templateDirectoryName = Path.GetDirectoryName(templateFullPath);
		string contentDir =  isShared ? @"In\Content_v1_0" : "Content_v1_0";
		string directoryName = Path.Combine(templateDirectoryName, contentDir);
		if(isShared) {
			System.IO.DirectoryInfo absRootDirInfo = new System.IO.DirectoryInfo(templateDirectoryName);
			absRootDirInfo = absRootDirInfo.Parent;
			string abstractionName = absRootDirInfo.Name;
			directoryName = directoryName.Replace(abstractionName, "AbstractionContent");
		}
		return directoryName;
	}
	
	void WriteContentToSingleOutput(string templateFullPath, string extension)
	{
		string templateDirectoryName = Path.GetDirectoryName(templateFullPath);
		string contentDir = "Out";
		string directoryName = Path.Combine(templateDirectoryName, contentDir);
		string contentFileName = System.IO.Path.GetFileNameWithoutExtension(templateFullPath) + extension;
		System.IO.DirectoryInfo absRootDirInfo = new System.IO.DirectoryInfo(templateDirectoryName);
		absRootDirInfo = absRootDirInfo.Parent;
		string abstractionName = absRootDirInfo.Name;
		directoryName = directoryName.Replace(abstractionName, "AbstractionContent");
		string contentFullName = Path.Combine(directoryName, contentFileName);
		string contentData = this.GenerationEnvironment.ToString();
		this.GenerationEnvironment.Clear();
		File.WriteAllText(contentFullName, contentData);
	}

	T LoadXml<T>(string xmlFileName) {
		using(FileStream fStream = File.OpenRead(xmlFileName)) {
			XmlSerializer serializer = new XmlSerializer(typeof(T));
			T result = (T) serializer.Deserialize(fStream);
			fStream.Close();
			return result;
		}
	}

	void BeginNamespace(string namespaceName) {
		
        
        #line default
        #line hidden
        
        #line 109 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 109 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));

        
        #line default
        #line hidden
        
        #line 109 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(" { \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 110 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
 
	}

	void EndBlock() {
		
        
        #line default
        #line hidden
        
        #line 114 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(" } ");

        
        #line default
        #line hidden
        
        #line 114 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"

	}

		
	static string RemoveScands(string sourceString) {
		return sourceString.Replace('ä', 'a').Replace('Ä', 'A').Replace('å', 'a').Replace('Å', 'A').Replace('ö', 'o').Replace('Ö', 'O');
	}
	
	public class GenerationItem
	{
		public string FileName;
		public string Content;
	}
	

        
        #line default
        #line hidden
        
        #line 1 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\..\..\abscommon\CommonInclude\Common\AbstractionOptions_namespace.ttinclude"

public class AbstractionOptions { 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8937
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AbstractionOptions.xsd")]
[System.Xml.Serialization.XmlRootAttribute("AbstractionOptions", Namespace="http://tempuri.org/AbstractionOptions.xsd", IsNullable=false)]
public partial class AbstractionOptionsType {
    
    private GeneralType generalField;
    
    /// <remarks/>
    public GeneralType General {
        get {
            return this.generalField;
        }
        set {
            this.generalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AbstractionOptions.xsd")]
public partial class GeneralType {
    
    private GeneralTypeShareLevel shareLevelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GeneralTypeShareLevel shareLevel {
        get {
            return this.shareLevelField;
        }
        set {
            this.shareLevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/AbstractionOptions.xsd")]
public enum GeneralTypeShareLevel {
    
    /// <remarks/>
    Local,
    
    /// <remarks/>
    Shared,
    
    /// <remarks/>
    Modular,
}
} 
        
        #line default
        #line hidden
        
        #line 1 "S:\UserData\Kalle\work\abs\TheBallPlatform\Abstractions\TheBallCoreABS\TheBallCore\TheBallCore_v1_0.ttinclude"

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("TheBallCoreAbstraction", Namespace="", IsNullable=false)]
public partial class TheBallCoreAbstractionType {
    
    private InstanceOfTheBallType instanceOfTheBallField;
    
    /// <remarks/>
    public InstanceOfTheBallType InstanceOfTheBall {
        get {
            return this.instanceOfTheBallField;
        }
        set {
            this.instanceOfTheBallField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InstanceOfTheBallType {
    
    private CoreInfrastructureType coreInfrastructureField;
    
    private DigitalInterfaceType digitalInterfaceField;
    
    private InformationObjectType[] informationModelField;
    
    private OperationType[] operationsField;
    
    private string semanticDomainNameField;
    
    /// <remarks/>
    public CoreInfrastructureType CoreInfrastructure {
        get {
            return this.coreInfrastructureField;
        }
        set {
            this.coreInfrastructureField = value;
        }
    }
    
    /// <remarks/>
    public DigitalInterfaceType DigitalInterface {
        get {
            return this.digitalInterfaceField;
        }
        set {
            this.digitalInterfaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("InformationObject", IsNullable=false)]
    public InformationObjectType[] InformationModel {
        get {
            return this.informationModelField;
        }
        set {
            this.informationModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable=false)]
    public OperationType[] Operations {
        get {
            return this.operationsField;
        }
        set {
            this.operationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string semanticDomainName {
        get {
            return this.semanticDomainNameField;
        }
        set {
            this.semanticDomainNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CoreInfrastructureType {
    
    private InformationObjectType[] informationModelField;
    
    private OperationType[] operationsField;
    
    private SubscriptionType[] subscriptionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("InformationObject", IsNullable=false)]
    public InformationObjectType[] InformationModel {
        get {
            return this.informationModelField;
        }
        set {
            this.informationModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable=false)]
    public OperationType[] Operations {
        get {
            return this.operationsField;
        }
        set {
            this.operationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Subscription", IsNullable=false)]
    public SubscriptionType[] Subscriptions {
        get {
            return this.subscriptionsField;
        }
        set {
            this.subscriptionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InformationObjectType {
    
    private AutomationDefinitionsType automationDefinitionField;
    
    private object itemField;
    
    private string nameField;
    
    private string designDescField;
    
    private bool provideCreateMethodField;
    
    private bool isIndependentMasterField;
    
    private InformationObjectTypeSerializationType serializationTypeField;
    
    public InformationObjectType() {
        this.provideCreateMethodField = true;
        this.isIndependentMasterField = false;
        this.serializationTypeField = InformationObjectTypeSerializationType.XML;
    }
    
    /// <remarks/>
    public AutomationDefinitionsType AutomationDefinition {
        get {
            return this.automationDefinitionField;
        }
        set {
            this.automationDefinitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CollectionFor", typeof(CollectionForType))]
    [System.Xml.Serialization.XmlElementAttribute("InformationItems", typeof(InformationItemsType))]
    [System.Xml.Serialization.XmlElementAttribute("InformationObjectContent", typeof(InformationObjectContentType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool provideCreateMethod {
        get {
            return this.provideCreateMethodField;
        }
        set {
            this.provideCreateMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isIndependentMaster {
        get {
            return this.isIndependentMasterField;
        }
        set {
            this.isIndependentMasterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(InformationObjectTypeSerializationType.XML)]
    public InformationObjectTypeSerializationType serializationType {
        get {
            return this.serializationTypeField;
        }
        set {
            this.serializationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AutomationDefinitionsType {
    
    private bool customIDProviderField;
    
    public AutomationDefinitionsType() {
        this.customIDProviderField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool customIDProvider {
        get {
            return this.customIDProviderField;
        }
        set {
            this.customIDProviderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SubViewType {
    
    private string nameField;
    
    private string viewNameField;
    
    private string viewItemPathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string viewName {
        get {
            return this.viewNameField;
        }
        set {
            this.viewNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string viewItemPath {
        get {
            return this.viewItemPathField;
        }
        set {
            this.viewItemPathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ViewFieldType {
    
    private string labelField;
    
    private ViewFieldTypeFieldType fieldTypeField;
    
    private ViewFieldTypeDisplayMode displayModeField;
    
    private string classNamesField;
    
    private string viewItemPathField;
    
    public ViewFieldType() {
        this.displayModeField = ViewFieldTypeDisplayMode.Display;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ViewFieldTypeFieldType fieldType {
        get {
            return this.fieldTypeField;
        }
        set {
            this.fieldTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ViewFieldTypeDisplayMode.Display)]
    public ViewFieldTypeDisplayMode displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string classNames {
        get {
            return this.classNamesField;
        }
        set {
            this.classNamesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string viewItemPath {
        get {
            return this.viewItemPathField;
        }
        set {
            this.viewItemPathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ViewFieldTypeFieldType {
    
    /// <remarks/>
    TextBox,
    
    /// <remarks/>
    TextBoxMultiline,
    
    /// <remarks/>
    TextBoxHiddenChars,
    
    /// <remarks/>
    CheckBox,
    
    /// <remarks/>
    DropdownList,
    
    /// <remarks/>
    MultiselectList,
    
    /// <remarks/>
    RadioButton,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ViewFieldTypeDisplayMode {
    
    /// <remarks/>
    Display,
    
    /// <remarks/>
    Editable,
    
    /// <remarks/>
    ToggleEditable,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InterfaceViewType {
    
    private object[] itemsField;
    
    private string nameField;
    
    private string rootObjectNameField;
    
    private bool autoRecurseSubViewsField;
    
    public InterfaceViewType() {
        this.autoRecurseSubViewsField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubView", typeof(SubViewType))]
    [System.Xml.Serialization.XmlElementAttribute("ViewField", typeof(ViewFieldType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rootObjectName {
        get {
            return this.rootObjectNameField;
        }
        set {
            this.rootObjectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool autoRecurseSubViews {
        get {
            return this.autoRecurseSubViewsField;
        }
        set {
            this.autoRecurseSubViewsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObjectInstanceType {
    
    private string nameField;
    
    private string interfaceObjectNameField;
    
    private bool isCollectionField;
    
    public ObjectInstanceType() {
        this.isCollectionField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string interfaceObjectName {
        get {
            return this.interfaceObjectNameField;
        }
        set {
            this.interfaceObjectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isCollection {
        get {
            return this.isCollectionField;
        }
        set {
            this.isCollectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InterfaceItemType {
    
    private string nameField;
    
    private InterfaceItemTypeLogicalDataType logicalDataTypeField;
    
    private bool isCollectionField;
    
    public InterfaceItemType() {
        this.isCollectionField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public InterfaceItemTypeLogicalDataType logicalDataType {
        get {
            return this.logicalDataTypeField;
        }
        set {
            this.logicalDataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isCollection {
        get {
            return this.isCollectionField;
        }
        set {
            this.isCollectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InterfaceItemTypeLogicalDataType {
    
    /// <remarks/>
    TrueOrFalse_Boolean,
    
    /// <remarks/>
    Text_Short,
    
    /// <remarks/>
    Text_Long,
    
    /// <remarks/>
    Number,
    
    /// <remarks/>
    Time_Date,
    
    /// <remarks/>
    Time_Time,
    
    /// <remarks/>
    Time_DateTime,
    
    /// <remarks/>
    Data_Binary,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InterfaceObjectType {
    
    private AutomationDefinitionsType automationDefinitionField;
    
    private object[] interfaceItemsField;
    
    private string nameField;
    
    private string designDescField;
    
    /// <remarks/>
    public AutomationDefinitionsType AutomationDefinition {
        get {
            return this.automationDefinitionField;
        }
        set {
            this.automationDefinitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("InterfaceItem", typeof(InterfaceItemType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ObjectInstance", typeof(ObjectInstanceType), IsNullable=false)]
    public object[] InterfaceItems {
        get {
            return this.interfaceItemsField;
        }
        set {
            this.interfaceItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DigitalInterfaceType {
    
    private InterfaceObjectType[] interfaceModelField;
    
    private InterfaceViewType[] interfaceViewsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("InterfaceObject", IsNullable=false)]
    public InterfaceObjectType[] InterfaceModel {
        get {
            return this.interfaceModelField;
        }
        set {
            this.interfaceModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("InterfaceView", IsNullable=false)]
    public InterfaceViewType[] InterfaceViews {
        get {
            return this.interfaceViewsField;
        }
        set {
            this.interfaceViewsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OperationParameterType {
    
    private string nameField;
    
    private string informationObjectNameField;
    
    private string informationItemNameField;
    
    private OperationParameterTypeInformationItemSource informationItemSourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string informationObjectName {
        get {
            return this.informationObjectNameField;
        }
        set {
            this.informationObjectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string informationItemName {
        get {
            return this.informationItemNameField;
        }
        set {
            this.informationItemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public OperationParameterTypeInformationItemSource informationItemSource {
        get {
            return this.informationItemSourceField;
        }
        set {
            this.informationItemSourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum OperationParameterTypeInformationItemSource {
    
    /// <remarks/>
    TriggeringObject,
    
    /// <remarks/>
    SubscribingObject,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InformationObjectTargetType {
    
    private string objectNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objectName {
        get {
            return this.objectNameField;
        }
        set {
            this.objectNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InformationItemTargetType {
    
    private string objectNameField;
    
    private string itemNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objectName {
        get {
            return this.objectNameField;
        }
        set {
            this.objectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemName {
        get {
            return this.itemNameField;
        }
        set {
            this.itemNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SubscriptionType {
    
    private object itemField;
    
    private OperationParameterType[] operationParameterField;
    
    private string triggeredOperationNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TriggeringInformationItem", typeof(InformationItemTargetType))]
    [System.Xml.Serialization.XmlElementAttribute("TriggeringObjectContent", typeof(InformationObjectTargetType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OperationParameter")]
    public OperationParameterType[] OperationParameter {
        get {
            return this.operationParameterField;
        }
        set {
            this.operationParameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string triggeredOperationName {
        get {
            return this.triggeredOperationNameField;
        }
        set {
            this.triggeredOperationNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OperationReturnValuesType {
    
    private VariableType[] returnValueField;
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
    public VariableType[] ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VariableType {
    
    private string nameField;
    
    private string dataTypeField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum VariableTypeState {
    
    /// <remarks/>
    underDesign,
    
    /// <remarks/>
    designApproved,
    
    /// <remarks/>
    implemented,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TargetType {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TargetDefinitionType {
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private MethodExecuteTypeAsyncSupportMode asyncSupportModeField;
    
    private string dataTypeField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    public TargetDefinitionType() {
        this.asyncSupportModeField = MethodExecuteTypeAsyncSupportMode.SyncOnly;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(MethodExecuteTypeAsyncSupportMode.SyncOnly)]
    public MethodExecuteTypeAsyncSupportMode asyncSupportMode {
        get {
            return this.asyncSupportModeField;
        }
        set {
            this.asyncSupportModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum MethodExecuteTypeAsyncSupportMode {
    
    /// <remarks/>
    SyncOnly,
    
    /// <remarks/>
    AsyncOnly,
    
    /// <remarks/>
    Both,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OperationExecuteType {
    
    private OperationSignatureType operationSignatureField;
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private VariableType[] returnValueField;
    
    private string nameField;
    
    private MethodExecuteTypeAsyncSupportMode asyncSupportModeField;
    
    private string targetOperationNameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    public OperationExecuteType() {
        this.asyncSupportModeField = MethodExecuteTypeAsyncSupportMode.SyncOnly;
    }
    
    /// <remarks/>
    public OperationSignatureType OperationSignature {
        get {
            return this.operationSignatureField;
        }
        set {
            this.operationSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
    public VariableType[] ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(MethodExecuteTypeAsyncSupportMode.SyncOnly)]
    public MethodExecuteTypeAsyncSupportMode asyncSupportMode {
        get {
            return this.asyncSupportModeField;
        }
        set {
            this.asyncSupportModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string targetOperationName {
        get {
            return this.targetOperationNameField;
        }
        set {
            this.targetOperationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OperationSignatureType {
    
    private LogicalInformationType[] parameterField;
    
    private LogicalInformationType returnValueField;
    
    private string nameField;
    
    private string logicalNamespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public LogicalInformationType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    public LogicalInformationType ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string logicalNamespace {
        get {
            return this.logicalNamespaceField;
        }
        set {
            this.logicalNamespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LogicalInformationType {
    
    private string nameField;
    
    private string logicalNamespaceField;
    
    private string logicalDatatypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string logicalNamespace {
        get {
            return this.logicalNamespaceField;
        }
        set {
            this.logicalNamespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string logicalDatatype {
        get {
            return this.logicalDatatypeField;
        }
        set {
            this.logicalDatatypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MethodExecuteType {
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private VariableType[] returnValueField;
    
    private string nameField;
    
    private MethodExecuteTypeAsyncSupportMode asyncSupportModeField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    public MethodExecuteType() {
        this.asyncSupportModeField = MethodExecuteTypeAsyncSupportMode.SyncOnly;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
    public VariableType[] ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(MethodExecuteTypeAsyncSupportMode.SyncOnly)]
    public MethodExecuteTypeAsyncSupportMode asyncSupportMode {
        get {
            return this.asyncSupportModeField;
        }
        set {
            this.asyncSupportModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ExecutionType {
    
    private object[] sequentialExecutionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("MethodExecute", typeof(MethodExecuteType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OperationExecute", typeof(OperationExecuteType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("TargetDefinition", typeof(TargetDefinitionType), IsNullable=false)]
    public object[] SequentialExecution {
        get {
            return this.sequentialExecutionField;
        }
        set {
            this.sequentialExecutionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ModificationType {
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ValidationType {
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ParametersType {
    
    private VariableType[] parameterField;
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public VariableType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Modification", typeof(ModificationType))]
    [System.Xml.Serialization.XmlElementAttribute("Validation", typeof(ValidationType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RequirementType {
    
    private object itemField;
    
    private string nameField;
    
    private RequirementTypeCategory categoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FreeformText", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Performance", typeof(RequirementTypePerformance))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RequirementTypeCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RequirementTypePerformance {
    
    private long maxMemoryBytesField;
    
    private bool maxMemoryBytesFieldSpecified;
    
    private decimal maxCPUTimeMsField;
    
    private bool maxCPUTimeMsFieldSpecified;
    
    private decimal maxTotalTimeMsField;
    
    private bool maxTotalTimeMsFieldSpecified;
    
    private long maxFileIOCountField;
    
    private bool maxFileIOCountFieldSpecified;
    
    private long maxFileIOBytesField;
    
    private bool maxFileIOBytesFieldSpecified;
    
    private decimal maxFileIOTimeMsField;
    
    private bool maxFileIOTimeMsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxMemoryBytes {
        get {
            return this.maxMemoryBytesField;
        }
        set {
            this.maxMemoryBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxMemoryBytesSpecified {
        get {
            return this.maxMemoryBytesFieldSpecified;
        }
        set {
            this.maxMemoryBytesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxCPUTimeMs {
        get {
            return this.maxCPUTimeMsField;
        }
        set {
            this.maxCPUTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxCPUTimeMsSpecified {
        get {
            return this.maxCPUTimeMsFieldSpecified;
        }
        set {
            this.maxCPUTimeMsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxTotalTimeMs {
        get {
            return this.maxTotalTimeMsField;
        }
        set {
            this.maxTotalTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxTotalTimeMsSpecified {
        get {
            return this.maxTotalTimeMsFieldSpecified;
        }
        set {
            this.maxTotalTimeMsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxFileIOCount {
        get {
            return this.maxFileIOCountField;
        }
        set {
            this.maxFileIOCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOCountSpecified {
        get {
            return this.maxFileIOCountFieldSpecified;
        }
        set {
            this.maxFileIOCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxFileIOBytes {
        get {
            return this.maxFileIOBytesField;
        }
        set {
            this.maxFileIOBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOBytesSpecified {
        get {
            return this.maxFileIOBytesFieldSpecified;
        }
        set {
            this.maxFileIOBytesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxFileIOTimeMs {
        get {
            return this.maxFileIOTimeMsField;
        }
        set {
            this.maxFileIOTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOTimeMsSpecified {
        get {
            return this.maxFileIOTimeMsFieldSpecified;
        }
        set {
            this.maxFileIOTimeMsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum RequirementTypeCategory {
    
    /// <remarks/>
    Customer,
    
    /// <remarks/>
    Architectural,
    
    /// <remarks/>
    Structural,
    
    /// <remarks/>
    Behavioral,
    
    /// <remarks/>
    Functional,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Non-functional")]
    Nonfunctional,
    
    /// <remarks/>
    Performance,
    
    /// <remarks/>
    Design,
    
    /// <remarks/>
    Derived,
    
    /// <remarks/>
    Allocated,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OperationSpecType {
    
    private RequirementType[] requirementsField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
    public RequirementType[] Requirements {
        get {
            return this.requirementsField;
        }
        set {
            this.requirementsField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OperationType {
    
    private OperationSpecType operationSpecField;
    
    private OperationSignatureType operationSignatureField;
    
    private ParametersType parametersField;
    
    private ExecutionType executionField;
    
    private OperationReturnValuesType operationReturnValuesField;
    
    private string nameField;
    
    /// <remarks/>
    public OperationSpecType OperationSpec {
        get {
            return this.operationSpecField;
        }
        set {
            this.operationSpecField = value;
        }
    }
    
    /// <remarks/>
    public OperationSignatureType OperationSignature {
        get {
            return this.operationSignatureField;
        }
        set {
            this.operationSignatureField = value;
        }
    }
    
    /// <remarks/>
    public ParametersType Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    public ExecutionType Execution {
        get {
            return this.executionField;
        }
        set {
            this.executionField = value;
        }
    }
    
    /// <remarks/>
    public OperationReturnValuesType OperationReturnValues {
        get {
            return this.operationReturnValuesField;
        }
        set {
            this.operationReturnValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InformationObjectContentType {
    
    private string fileExtensionField;
    
    private string originalFileNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileExtension {
        get {
            return this.fileExtensionField;
        }
        set {
            this.fileExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string originalFileName {
        get {
            return this.originalFileNameField;
        }
        set {
            this.originalFileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CollectionForType {
    
    private string contentInformationObjectNameField;
    
    private CollectionForTypeCollectionType collectionTypeField;
    
    public CollectionForType() {
        this.collectionTypeField = CollectionForTypeCollectionType.Independent;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contentInformationObjectName {
        get {
            return this.contentInformationObjectNameField;
        }
        set {
            this.contentInformationObjectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(CollectionForTypeCollectionType.Independent)]
    public CollectionForTypeCollectionType collectionType {
        get {
            return this.collectionTypeField;
        }
        set {
            this.collectionTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum CollectionForTypeCollectionType {
    
    /// <remarks/>
    Independent,
    
    /// <remarks/>
    Master,
    
    /// <remarks/>
    DerivedFromMaster,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InformationItemsType {
    
    private InformationItemType[] informationItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InformationItem")]
    public InformationItemType[] InformationItem {
        get {
            return this.informationItemField;
        }
        set {
            this.informationItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InformationItemType {
    
    private string nameField;
    
    private InformationItemTypeLogicalDataType logicalDataTypeField;
    
    private string informationObjectNameField;
    
    private string objectLinkTargetTypeField;
    
    private bool isCollectionField;
    
    private int fieldOrderNumberField;
    
    public InformationItemType() {
        this.informationObjectNameField = "";
        this.objectLinkTargetTypeField = "";
        this.isCollectionField = false;
        this.fieldOrderNumberField = 0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public InformationItemTypeLogicalDataType logicalDataType {
        get {
            return this.logicalDataTypeField;
        }
        set {
            this.logicalDataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string informationObjectName {
        get {
            return this.informationObjectNameField;
        }
        set {
            this.informationObjectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string objectLinkTargetType {
        get {
            return this.objectLinkTargetTypeField;
        }
        set {
            this.objectLinkTargetTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isCollection {
        get {
            return this.isCollectionField;
        }
        set {
            this.isCollectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int fieldOrderNumber {
        get {
            return this.fieldOrderNumberField;
        }
        set {
            this.fieldOrderNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InformationItemTypeLogicalDataType {
    
    /// <remarks/>
    TrueOrFalse_Boolean,
    
    /// <remarks/>
    Text_Short,
    
    /// <remarks/>
    Text_Long,
    
    /// <remarks/>
    Number_Integer,
    
    /// <remarks/>
    Number_ExactDecimal,
    
    /// <remarks/>
    Number_ApproxDecimal,
    
    /// <remarks/>
    Time_Date,
    
    /// <remarks/>
    Time_Time,
    
    /// <remarks/>
    Time_DateTime,
    
    /// <remarks/>
    Data_Binary,
    
    /// <remarks/>
    InformationObject,
    
    /// <remarks/>
    ObjectLink,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InformationObjectTypeSerializationType {
    
    /// <remarks/>
    XML,
    
    /// <remarks/>
    JSON,
    
    /// <remarks/>
    Binary,
    
    /// <remarks/>
    Custom,
    
    /// <remarks/>
    ProtoBuf,
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class KnockoutDustHtmlViewGenerator_v1_0Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
