//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace TheBallCore_v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TheBallCoreAbstraction {
        
        private TheBallCoreAbstractionInstanceOfTheBall instanceOfTheBallField;
        
        /// <remarks/>
        public TheBallCoreAbstractionInstanceOfTheBall InstanceOfTheBall {
            get {
                return this.instanceOfTheBallField;
            }
            set {
                this.instanceOfTheBallField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBall {
        
        private ClassType[] informationModelField;
        
        private OperationType[] operationsField;
        
        private TheBallCoreAbstractionInstanceOfTheBallSubscription[] subscriptionsField;
        
        private TheBallCoreAbstractionInstanceOfTheBallMonitor[] monitoringField;
        
        private string semanticDomainNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InformationObject", IsNullable=false)]
        public ClassType[] InformationModel {
            get {
                return this.informationModelField;
            }
            set {
                this.informationModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable=false)]
        public OperationType[] Operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Subscription", IsNullable=false)]
        public TheBallCoreAbstractionInstanceOfTheBallSubscription[] Subscriptions {
            get {
                return this.subscriptionsField;
            }
            set {
                this.subscriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Monitor", IsNullable=false)]
        public TheBallCoreAbstractionInstanceOfTheBallMonitor[] Monitoring {
            get {
                return this.monitoringField;
            }
            set {
                this.monitoringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string semanticDomainName {
            get {
                return this.semanticDomainNameField;
            }
            set {
                this.semanticDomainNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClassType {
        
        private object itemField;
        
        private string nameField;
        
        private string designDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InformationItems", typeof(PropertiesType))]
        [System.Xml.Serialization.XmlElementAttribute("InformationObjectContent", typeof(InformationObjectContentType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertiesType {
        
        private PropertyType[] informationItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InformationItem")]
        public PropertyType[] InformationItem {
            get {
                return this.informationItemField;
            }
            set {
                this.informationItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertyType {
        
        private string nameField;
        
        private string logicalDataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string logicalDataType {
            get {
                return this.logicalDataTypeField;
            }
            set {
                this.logicalDataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationReturnValuesType {
        
        private VariableType[] returnValueField;
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
        public VariableType[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VariableType {
        
        private string nameField;
        
        private string dataTypeField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum VariableTypeState {
        
        /// <remarks/>
        underDesign,
        
        /// <remarks/>
        designApproved,
        
        /// <remarks/>
        implemented,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TargetType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TargetDefinitionType {
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        private string nameField;
        
        private string dataTypeField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationExecuteType {
        
        private OperationSignatureType operationSignatureField;
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        private VariableType[] returnValueField;
        
        private string nameField;
        
        private string targetOperationNameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        public OperationSignatureType OperationSignature {
            get {
                return this.operationSignatureField;
            }
            set {
                this.operationSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
        public VariableType[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetOperationName {
            get {
                return this.targetOperationNameField;
            }
            set {
                this.targetOperationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationSignatureType {
        
        private LogicalInformationType[] parameterField;
        
        private LogicalInformationType returnValueField;
        
        private string nameField;
        
        private string logicalNamespaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public LogicalInformationType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        public LogicalInformationType ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string logicalNamespace {
            get {
                return this.logicalNamespaceField;
            }
            set {
                this.logicalNamespaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogicalInformationType {
        
        private string nameField;
        
        private string logicalNamespaceField;
        
        private string logicalDatatypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string logicalNamespace {
            get {
                return this.logicalNamespaceField;
            }
            set {
                this.logicalNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string logicalDatatype {
            get {
                return this.logicalDatatypeField;
            }
            set {
                this.logicalDatatypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MethodExecuteType {
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        private VariableType[] returnValueField;
        
        private string nameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
        public VariableType[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecutionType {
        
        private object[] sequentialExecutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MethodExecute", typeof(MethodExecuteType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OperationExecute", typeof(OperationExecuteType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TargetDefinition", typeof(TargetDefinitionType), IsNullable=false)]
        public object[] SequentialExecution {
            get {
                return this.sequentialExecutionField;
            }
            set {
                this.sequentialExecutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificationType {
        
        private TargetType[] targetField;
        
        private string nameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidationType {
        
        private TargetType[] targetField;
        
        private string nameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParametersType {
        
        private VariableType[] parameterField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public VariableType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Modification", typeof(ModificationType))]
        [System.Xml.Serialization.XmlElementAttribute("Validation", typeof(ValidationType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequirementType {
        
        private object itemField;
        
        private string nameField;
        
        private RequirementTypeCategory categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FreeformText", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Performance", typeof(RequirementTypePerformance))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RequirementTypeCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RequirementTypePerformance {
        
        private long maxMemoryBytesField;
        
        private bool maxMemoryBytesFieldSpecified;
        
        private decimal maxCPUTimeMsField;
        
        private bool maxCPUTimeMsFieldSpecified;
        
        private decimal maxTotalTimeMsField;
        
        private bool maxTotalTimeMsFieldSpecified;
        
        private long maxFileIOCountField;
        
        private bool maxFileIOCountFieldSpecified;
        
        private long maxFileIOBytesField;
        
        private bool maxFileIOBytesFieldSpecified;
        
        private decimal maxFileIOTimeMsField;
        
        private bool maxFileIOTimeMsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maxMemoryBytes {
            get {
                return this.maxMemoryBytesField;
            }
            set {
                this.maxMemoryBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxMemoryBytesSpecified {
            get {
                return this.maxMemoryBytesFieldSpecified;
            }
            set {
                this.maxMemoryBytesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxCPUTimeMs {
            get {
                return this.maxCPUTimeMsField;
            }
            set {
                this.maxCPUTimeMsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxCPUTimeMsSpecified {
            get {
                return this.maxCPUTimeMsFieldSpecified;
            }
            set {
                this.maxCPUTimeMsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxTotalTimeMs {
            get {
                return this.maxTotalTimeMsField;
            }
            set {
                this.maxTotalTimeMsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxTotalTimeMsSpecified {
            get {
                return this.maxTotalTimeMsFieldSpecified;
            }
            set {
                this.maxTotalTimeMsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maxFileIOCount {
            get {
                return this.maxFileIOCountField;
            }
            set {
                this.maxFileIOCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxFileIOCountSpecified {
            get {
                return this.maxFileIOCountFieldSpecified;
            }
            set {
                this.maxFileIOCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maxFileIOBytes {
            get {
                return this.maxFileIOBytesField;
            }
            set {
                this.maxFileIOBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxFileIOBytesSpecified {
            get {
                return this.maxFileIOBytesFieldSpecified;
            }
            set {
                this.maxFileIOBytesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxFileIOTimeMs {
            get {
                return this.maxFileIOTimeMsField;
            }
            set {
                this.maxFileIOTimeMsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxFileIOTimeMsSpecified {
            get {
                return this.maxFileIOTimeMsFieldSpecified;
            }
            set {
                this.maxFileIOTimeMsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RequirementTypeCategory {
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Architectural,
        
        /// <remarks/>
        Structural,
        
        /// <remarks/>
        Behavioral,
        
        /// <remarks/>
        Functional,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Non-functional")]
        Nonfunctional,
        
        /// <remarks/>
        Performance,
        
        /// <remarks/>
        Design,
        
        /// <remarks/>
        Derived,
        
        /// <remarks/>
        Allocated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationSpecType {
        
        private RequirementType[] requirementsField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
        public RequirementType[] Requirements {
            get {
                return this.requirementsField;
            }
            set {
                this.requirementsField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationType {
        
        private OperationSpecType operationSpecField;
        
        private OperationSignatureType operationSignatureField;
        
        private ParametersType parametersField;
        
        private ExecutionType executionField;
        
        private OperationReturnValuesType operationReturnValuesField;
        
        private string nameField;
        
        /// <remarks/>
        public OperationSpecType OperationSpec {
            get {
                return this.operationSpecField;
            }
            set {
                this.operationSpecField = value;
            }
        }
        
        /// <remarks/>
        public OperationSignatureType OperationSignature {
            get {
                return this.operationSignatureField;
            }
            set {
                this.operationSignatureField = value;
            }
        }
        
        /// <remarks/>
        public ParametersType Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        public ExecutionType Execution {
            get {
                return this.executionField;
            }
            set {
                this.executionField = value;
            }
        }
        
        /// <remarks/>
        public OperationReturnValuesType OperationReturnValues {
            get {
                return this.operationReturnValuesField;
            }
            set {
                this.operationReturnValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InformationObjectContentType {
        
        private string fileExtensionField;
        
        private string originalFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string originalFileName {
            get {
                return this.originalFileNameField;
            }
            set {
                this.originalFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallSubscription {
        
        private object itemField;
        
        private TheBallCoreAbstractionInstanceOfTheBallSubscriptionOperationParameter[] operationParameterField;
        
        private string triggeredOperationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TriggeringInformationItem", typeof(TheBallCoreAbstractionInstanceOfTheBallSubscriptionTriggeringInformationItem))]
        [System.Xml.Serialization.XmlElementAttribute("TriggeringObjectContent", typeof(TheBallCoreAbstractionInstanceOfTheBallSubscriptionTriggeringObjectContent))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationParameter")]
        public TheBallCoreAbstractionInstanceOfTheBallSubscriptionOperationParameter[] OperationParameter {
            get {
                return this.operationParameterField;
            }
            set {
                this.operationParameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string triggeredOperationName {
            get {
                return this.triggeredOperationNameField;
            }
            set {
                this.triggeredOperationNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallSubscriptionTriggeringInformationItem {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallSubscriptionTriggeringObjectContent {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallSubscriptionOperationParameter {
        
        private string nameField;
        
        private string informationItemNameField;
        
        private TheBallCoreAbstractionInstanceOfTheBallSubscriptionOperationParameterInformationItemSource informationItemSourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string informationItemName {
            get {
                return this.informationItemNameField;
            }
            set {
                this.informationItemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TheBallCoreAbstractionInstanceOfTheBallSubscriptionOperationParameterInformationItemSource informationItemSource {
            get {
                return this.informationItemSourceField;
            }
            set {
                this.informationItemSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum TheBallCoreAbstractionInstanceOfTheBallSubscriptionOperationParameterInformationItemSource {
        
        /// <remarks/>
        TriggeringObject,
        
        /// <remarks/>
        SubscribingObject,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallMonitor {
        
        private object itemField;
        
        private TheBallCoreAbstractionInstanceOfTheBallMonitorOperationParameter[] operationParameterField;
        
        private string monitoringOperationNameField;
        
        private int monitoringFrequencyInSecondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MonitoredInformationItem", typeof(TheBallCoreAbstractionInstanceOfTheBallMonitorMonitoredInformationItem))]
        [System.Xml.Serialization.XmlElementAttribute("MonitoredObjectContent", typeof(TheBallCoreAbstractionInstanceOfTheBallMonitorMonitoredObjectContent))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationParameter")]
        public TheBallCoreAbstractionInstanceOfTheBallMonitorOperationParameter[] OperationParameter {
            get {
                return this.operationParameterField;
            }
            set {
                this.operationParameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string monitoringOperationName {
            get {
                return this.monitoringOperationNameField;
            }
            set {
                this.monitoringOperationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int monitoringFrequencyInSeconds {
            get {
                return this.monitoringFrequencyInSecondsField;
            }
            set {
                this.monitoringFrequencyInSecondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallMonitorMonitoredInformationItem {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallMonitorMonitoredObjectContent {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TheBallCoreAbstractionInstanceOfTheBallMonitorOperationParameter {
        
        private string nameField;
        
        private string informationItemNameField;
        
        private TheBallCoreAbstractionInstanceOfTheBallMonitorOperationParameterInformationItemSource informationItemSourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string informationItemName {
            get {
                return this.informationItemNameField;
            }
            set {
                this.informationItemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TheBallCoreAbstractionInstanceOfTheBallMonitorOperationParameterInformationItemSource informationItemSource {
            get {
                return this.informationItemSourceField;
            }
            set {
                this.informationItemSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum TheBallCoreAbstractionInstanceOfTheBallMonitorOperationParameterInformationItemSource {
        
        /// <remarks/>
        TriggeringObject,
        
        /// <remarks/>
        SubscribingObject,
    }
}
